### ISSUE TITLE
Editor crashes upon selecting certain types of textures

### ISSUE THREAD

**Issue by LatteXIV** [metallicafan212/UE2SelectionFixes#1] opened 2024-06-22 19:11 UTC
The editor appears to crash upon clicking on textures with shaders, combiners, etc in the Texture Browser.

Regular textures appear to work fine. If a map has these textures pre-applied it loads without issue. 

Reverting back to the original .DLL does resolve the issue.

Edit to add: this is using a default UT2004 installation via Steam, with KFmod 2.52 installed as well.

![image (1)](https://github.com/metallicafan212/UE2SelectionFixes/assets/74606455/e4fe1d7f-5388-4d47-a43b-6a250ad1105d)

![image (2)](https://github.com/metallicafan212/UE2SelectionFixes/assets/74606455/2caef76d-8ecf-40ca-a0cb-54d06c8c5907)

**Comment by metallicafan212** [comment] 2024-06-22 19:14
@LatteXIV In preferences, disable the SelectionFix bool and see if the crash still exists (this reverts the selection code back to the stock slow one)

**Comment by LatteXIV** [comment] 2024-06-22 19:41
Setting EnableSelectionFix to false does also resolve the issue.

Setting EnableSelectionFix to true and DebugSelectionFix to true also resolves the issue - though everything in the Texture Browser turns red. 

Interestingly, setting EnableSelectionFix to false and then back to True somewhat fixes the crashing - it does not allow me to apply the blended texture. It just deselects the surface that I clicked on. Clicking a _different_ blended texture then crashes the Editor.

![image](https://github.com/metallicafan212/UE2SelectionFixes/assets/74606455/69b9a825-b247-49f8-bb0f-3d7230080053)

**Comment by metallicafan212** [comment] 2024-06-22 19:44
The debug bool is working as intended, it showcases how the fix works behind the scenes (renders the objects using the index as a color).

I'll look into this crash later. Remember to turn off the debug bool otherwise you'll have selection delays while it tries to show you what it did 🙂

**Comment by metallicafan212** [comment] 2024-06-29 05:30
@LatteXIV Try the latest UT2k4 file https://github.com/metallicafan212/UE2SelectionFixes/releases/tag/v0.2-Alpha-2k4

**Comment by metallicafan212** [comment] 2024-09-21 22:56
Closing as there's been no further comment and should be fixed

**Closed as completed by metallicafan212** 2024-09-21 22:56 UTC
